services:
  pangolin-site:
    image: fosrl/pangolin-cli
    container_name: pangolin-site
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=${PANGOLIN_ENDPOINT:-https://pangolin.fossorial.io}
      - SITE_ID=${SITE_ID:?Site ID}
      - SITE_SECRET=${SITE_SECRET:?Site Secret}
      - DISABLE_CLIENTS=${DISABLE_CLIENTS:-false}
