name: termix

services:
  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix
    restart: unless-stopped
    ports:
      - '${COMPOSE_PORT_TERMIX:-2280}:8080'
    environment:
      PORT: '8080'
    volumes:
      - termix-data:/app/data
    depends_on:
      - guacd
    networks:
      - termix-net

  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacd
    restart: unless-stopped
    ports:
      - "${COMPOSE_PORT_GUACD:-4822}:4822"
    networks:
      - termix-net

volumes:
  termix-data:
    driver: local

networks:
  termix-net:
    driver: bridge
